# Generated by Django 5.0.2 on 2024-05-26 09:45

import ludoapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=122)),
                ('phone', models.BigIntegerField(validators=[ludoapp.models.validate_phone_length])),
                ('player_email', models.EmailField(max_length=122)),
                ('password', models.CharField(max_length=122)),
                ('confirm_password', models.CharField(max_length=122)),
            ],
            options={
                'db_table': 'player',
                'ordering': ['player_name'],
            },
        ),
    ]
