# Generated by Django 5.0.2 on 2024-05-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='player',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
