# Generated by Django 5.0.2 on 2024-05-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludoapp', '0002_player_back_image_player_front_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='back_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='front_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
