# Generated by Django 5.0.2 on 2024-05-29 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ludoapp', '0004_battle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='opponent',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='room_code',
        ),
    ]
