# Generated by Django 5.0.2 on 2024-05-30 17:38

import ludoapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludoapp', '0005_remove_battle_creator_remove_battle_opponent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.AddField(
            model_name='player',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='phone',
            field=models.BigIntegerField(primary_key=True, serialize=False, validators=[ludoapp.models.validate_phone_length]),
        ),
    ]
