# Generated by Django 5.0.2 on 2024-05-31 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludoapp', '0006_remove_player_id_player_approved_alter_player_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='created_battles', to='ludoapp.player'),
        ),
    ]
