# Generated by Django 5.0.2 on 2024-06-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludoapp', '0007_battle_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
