# Generated by Django 5.0.2 on 2024-06-01 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludoapp', '0008_player_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joined_battles', to='ludoapp.player'),
        ),
    ]
