# Generated by Django 5.0.2 on 2024-06-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludoapp', '0009_battle_opponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
    ]
