# Generated by Django 5.0.2 on 2024-06-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludoapp', '0012_withdrawalaccount_withdraw_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalaccount',
            name='withdraw_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
